# -*- coding: utf-8 -*-
"""SURENDHAR B AI ML .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UWpOSsZlHXgIPETA3meyJDUR5zeUe_cK

Project Structure

purplemerit-war-room/
├── README.md
├── requirements.txt
├── main.py                 # Orchestrator & main execution
├── agents/
│   ├── __init__.py
│   ├── product_manager.py
│   ├── data_analyst.py
│   ├── marketing_comms.py
│   └── risk_critic.py
├── tools/
│   ├── __init__.py
│   ├── metrics_analyzer.py
│   ├── sentiment_analyzer.py
│   └── trend_detector.py
├── data/
│   ├── mock_dashboard.csv
│   ├── user_feedback.json
│   └── release_notes.md
├── output/
│   └── launch_decision.json
└── config.yaml

requirements.txt

pandas==2.2.2
numpy==1.26.4
scikit-learn==1.5.1
vaderSentiment==3.3.2
matplotlib==3.8.4
seaborn==0.13.2
pyyaml==6.0.1
python-dateutil==2.9.0.post0
scipy==1.13.1

config.yam

launch_window:
  start_date: "2026-04-01"
  end_date: "2026-04-08"
  
success_criteria:
  dau_drop_threshold: 0.15
  retention_drop_threshold: 0.10
  crash_rate_threshold: 0.02
  latency_threshold_p95: 500
  negative_sentiment_threshold: 0.40
  
agents:
  timeout_seconds: 30

2.Mock Data Generation & Tools
"""

#data/mock_dashboard.csv

"""date,day,dau,wau,activation_rate,d1_retention,d7_retention,crash_rate,api_latency_p95,payment_success_rate,support_tickets,feature_adoption,cancellations
2026-03-25,Pre-launch,12500,28500,0.32,0.45,0.22,0.008,245,0.98,45,0.00,12
2026-03-26,Pre-launch,12650,28700,0.33,0.46,0.23,0.007,238,0.99,42,0.00,11
2026-03-27,Pre-launch,12400,28400,0.31,0.44,0.21,0.009,252,0.97,48,0.00,13
2026-03-28,Pre-launch,12700,28900,0.34,0.47,0.24,0.006,231,0.98,40,0.00,10
2026-03-29,Pre-launch,12800,29100,0.33,0.46,0.23,0.008,247,0.99,43,0.00,9
2026-03-30,Pre-launch,12600,28800,0.32,0.45,0.22,0.007,240,0.98,46,0.00,12
2026-03-31,Pre-launch,12550,28600,0.33,0.46,0.23,0.009,255,0.97,44,0.00,11
2026-04-01,Day1,11800,28400,0.29,0.42,0.20,0.012,320,0.95,65,0.15,18
2026-04-02,Day2,11550,28200,0.28,0.40,0.19,0.018,450,0.93,92,0.12,25
2026-04-03,Day3,11200,27900,0.27,0.39,0.18,0.025,580,0.91,128,0.10,32
2026-04-04,Day4,11050,27600,0.26,0.38,0.17,0.022,510,0.92,115,0.11,28
2026-04-05,Day5,11300,27800,0.27,0.39,0.18,0.019,470,0.94,98,0.13,22
2026-04-06,Day6,11450,28000,0.28,0.40,0.19,0.016,410,0.95,85,0.14,19
2026-04-07,Day7,11600,28200,0.29,0.41,0.20,0.014,380,0.96,72,0.16,16
"""



"""data/user_feedback.json"""

[
  "New feature is confusing, keeps crashing on mobile",
  "Love the new UI! Much faster than before",
  "Payment flow broken - cards not working",
  "Feature adoption is slow but promising",
  "API timeouts ruining my workflow",
  "Great addition! Bookmarks work perfectly",
  "Crash rate doubled since launch",
  "Support tickets through the roof",
  "D1 retention dropping fast",
  "New search is lightning fast",
  "Mobile app crashes on feature load",
  "Payments failing 30% of time",
  "Latency issues killing productivity",
  "UI looks modern but functionality broken",
  "Feature has potential but needs polish",
  "Cancellations spiking since launch",
  "Support overwhelmed with crash reports",
  "New analytics dashboard is excellent",
  "Feature funnel completion too low",
  "Rollback needed - too many bugs",
  "Positive change overall despite issues",
  "DAU dropping steadily",
  "Error rates unacceptable for production",
  "Communication lacking on known issues",
  "Worth the wait - core functionality solid",
  "Mobile experience ruined by crashes",
  "Payments need immediate fix",
  "Great feature when it works",
  "Too many bugs for prime time",
  "Support response time doubled",
  "Launch feels rushed"
]

"""tools/metrics_analyzer.py"""

import pandas as pd
import numpy as np
from scipy import stats
from sklearn.ensemble import IsolationForest
import json
from typing import Dict, List, Tuple

class MetricsAnalyzer:
    def __init__(self, dashboard_path: str):
        self.df = pd.read_csv(dashboard_path)
        self.df['date'] = pd.to_datetime(self.df['date'])
        self.baseline_period = self.df[self.df['day'] == 'Pre-launch']
        self.launch_period = self.df[self.df['day'] != 'Pre-launch']

    def detect_anomalies(self, metric: str, window: int = 7) -> Dict:
        """Detect anomalies using Isolation Forest"""
        values = self.df[metric].values.reshape(-1, 1)
        iso_forest = IsolationForest(contamination=0.1, random_state=42)
        anomalies = iso_forest.fit_predict(values)

        anomaly_dates = self.df[anomalies == -1]['date'].dt.date.tolist()
        return {
            'metric': metric,
            'anomaly_dates': anomaly_dates,
            'severity': 'HIGH' if len(anomaly_dates) > 2 else 'MEDIUM'
        }

    def calculate_trend_changes(self) -> Dict[str, Dict]:
        """Calculate percentage change from baseline to launch period"""
        trends = {}
        for metric in ['dau', 'd1_retention', 'crash_rate', 'api_latency_p95',
                      'payment_success_rate', 'feature_adoption']:
            baseline_mean = self.baseline_period[metric].mean()
            launch_mean = self.launch_period[metric].mean()
            change_pct = ((launch_mean - baseline_mean) / baseline_mean) * 100

            trends[metric] = {
                'baseline': baseline_mean,
                'launch': launch_mean,
                'change_pct': round(change_pct, 2),
                'direction': 'DOWN' if change_pct < 0 else 'UP',
                'concerning': change_pct < -5 or (metric == 'crash_rate' and change_pct > 20)
            }
        return trends

    def get_key_metrics_summary(self) -> Dict:
        """Get critical metrics at a glance"""
        latest = self.df.iloc[-1]
        return {
            'latest_dau': latest['dau'],
            'dau_change_pct': round((latest['dau'] - self.baseline_period['dau'].mean()) /
                                  self.baseline_period['dau'].mean() * 100, 1),
            'crash_rate': latest['crash_rate'],
            'latency_p95': latest['api_latency_p95'],
            'payment_success': latest['payment_success_rate'],
            'support_tickets': latest['support_tickets'],
            'feature_adoption': latest['feature_adoption']
        }



"""tools/sentiment_analyzer.py"""

!pip install VADER-Sentiment

import sys
!{sys.executable} -m pip install vaderSentiment

from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
import json
import re
from collections import Counter
from typing import Dict, List

class SentimentAnalyzer:
    def __init__(self, feedback_path: str):
        with open(feedback_path, 'r') as f:
            self.feedback = json.load(f)
        self.analyzer = SentimentIntensityAnalyzer()

    def analyze_sentiment(self) -> Dict:
        """Analyze sentiment across all feedback"""
        sentiments = []
        keywords = []

        for feedback in self.feedback:
            score = self.analyzer.polarity_scores(feedback)
            sentiments.append(score)

            # Extract keywords
            words = re.findall(r'\b\w+\b', feedback.lower())
            keywords.extend([w for w in words if len(w) > 3])

        avg_sentiment = sum(s['compound'] for s in sentiments) / len(sentiments)

        keyword_counts = Counter(keywords).most_common(10)

        return {
            'overall_score': round(avg_sentiment, 3),
            'sentiment_category': self._categorize_sentiment(avg_sentiment),
            'positive_ratio': len([s for s in sentiments if s['compound'] > 0.05]) / len(sentiments),
            'negative_ratio': len([s for s in sentiments if s['compound'] < -0.05]) / len(sentiments),
            'top_keywords': keyword_counts,
            'sentiment_trend': 'DETERIORATING' if avg_sentiment < -0.1 else 'STABLE'
        }

    def _categorize_sentiment(self, score: float) -> str:
        if score >= 0.05:
            return "POSITIVE"
        elif score <= -0.05:
            return "NEGATIVE"
        else:
            return "NEUTRAL"



"""3. Agent Implementations"""

import sys
import os

# Add current directory to Python path
sys.path.append(os.getcwd())

import os

os.makedirs("tools", exist_ok=True)

with open("tools/metrics_analyzer.py", "w") as f:
    f.write("""
class MetricsAnalyzer:
    def analyze(self, data):
        return {"result": "ok", "input": data}
""")

from typing import Dict, Any
from tools.metrics_analyzer import MetricsAnalyzer
import yaml

class ProductManagerAgent:
    def __init__(self, config_path: str):
        with open(config_path, 'r') as f:
            self.config = yaml.safe_load(f)

    def analyze_success_criteria(self, metrics_tool: MetricsAnalyzer) -> Dict[str, Any]:
        """Define success criteria and evaluate against metrics"""
        trends = metrics_tool.calculate_trend_changes()
        key_metrics = metrics_tool.get_key_metrics_summary()

        # Evaluate against predefined thresholds
        issues = []
        if trends['dau']['change_pct'] < -self.config['success_criteria']['dau_drop_threshold'] * 100:
            issues.append("DAU drop exceeds threshold")
        if key_metrics['crash_rate'] > self.config['success_criteria']['crash_rate_threshold']:
            issues.append("Crash rate critical")

        success_score = max(0, 100 + sum(trends[metric]['change_pct'] for metric in trends) / len(trends))

        return {
            'success_criteria_met': len(issues) == 0,
            'key_issues': issues,
            'success_score': round(success_score, 1),
            'recommendation': 'PAUSE' if len(issues) > 1 else 'PROCEED_WITH_MONITORING',
            'user_impact': 'HIGH' if 'DAU' in ' '.join(issues) else 'MEDIUM'
        }



"""agents/data_analyst.py"""

import os

os.makedirs("tools", exist_ok=True)

with open("tools/sentiment_analyzer.py", "w") as f:
    f.write("""
class SentimentAnalyzer:
    def analyze(self, text):
        # simple dummy sentiment logic
        if "good" in text.lower():
            return {"sentiment": "positive"}
        elif "bad" in text.lower():
            return {"sentiment": "negative"}
        else:
            return {"sentiment": "neutral"}
""")

from typing import Dict, List
from tools.metrics_analyzer import MetricsAnalyzer
from tools.sentiment_analyzer import SentimentAnalyzer

class DataAnalystAgent:
    def __init__(self):
        pass

    def comprehensive_analysis(self, metrics_tool: MetricsAnalyzer,
                            sentiment_tool: SentimentAnalyzer) -> Dict:
        """Full quantitative analysis with statistical significance"""
        trends = metrics_tool.calculate_trend_changes()
        anomalies = [metrics_tool.detect_anomalies(metric) for metric in
                    ['crash_rate', 'api_latency_p95', 'dau']]
        sentiment = sentiment_tool.analyze_sentiment()
        key_metrics = metrics_tool.get_key_metrics_summary()

        # Statistical significance test
        p_values = {}
        for metric in ['dau', 'd1_retention', 'crash_rate']:
            baseline = metrics_tool.baseline_period[metric]
            launch = metrics_tool.launch_period[metric]
            t_stat, p_val = stats.ttest_ind(launch, baseline)
            p_values[metric] = round(p_val, 4)

        confidence = self._calculate_confidence(p_values, sentiment, anomalies)

        return {
            'trends': trends,
            'anomalies': anomalies,
            'sentiment': sentiment,
            'statistical_significance': p_values,
            'confidence_score': confidence,
            'key_takeaways': self._generate_takeaways(trends, sentiment, anomalies)
        }

    def _calculate_confidence(self, p_values: Dict, sentiment: Dict,
                            anomalies: List) -> float:
        sig_changes = sum(1 for p in p_values.values() if p < 0.05)
        anomaly_severity = sum(1 for a in anomalies if a['severity'] == 'HIGH')
        sentiment_impact = 1 if sentiment['overall_score'] < -0.2 else 0.5

        return max(0, 100 - (sig_changes * 20 + anomaly_severity * 15 + sentiment_impact * 20))

    def _generate_takeaways(self, trends: Dict, sentiment: Dict, anomalies: List) -> List[str]:
        takeaways = []
        concerning_metrics = [k for k, v in trends.items() if v['concerning']]
        if concerning_metrics:
            takeaways.append(f"Concerning metrics: {', '.join(concerning_metrics)}")
        if sentiment['negative_ratio'] > 0.4:
            takeaways.append("High negative sentiment detected")
        return takeaways





"""agents/marketing_comms.py"""

from typing import Dict, List
from tools.sentiment_analyzer import SentimentAnalyzer

class MarketingCommsAgent:
    def __init__(self):
        pass

    def craft_communication_plan(self, sentiment_data: Dict,
                               key_issues: List[str]) -> Dict:
        """Generate messaging strategy based on data"""
        sentiment = sentiment_data['sentiment']
        severity = 'CRITICAL' if sentiment['negative_ratio'] > 0.5 else 'HIGH'

        messages = {
            'internal': "Acknowledging launch issues, prioritizing fixes. Monitoring closely.",
            'external': "We're aware of some launch hiccups and actively resolving.",
            'channels': ['Status page', 'Twitter', 'Customer email'] if severity == 'CRITICAL' else ['Status page']
        }

        if 'payment' in ' '.join(key_issues).lower():
            messages['urgent'] = "Payment issues - highest priority"

        return {
            'communication_tier': severity,
            'messaging': messages,
            'timing': 'IMMEDIATE' if severity == 'CRITICAL' else 'WITHIN_4H',
            'monitoring_keywords': ['crash', 'payment', 'latency', 'slow']
        }



"""agents/risk_critic.py"""

from typing import Dict, List

class RiskCriticAgent:
    def __init__(self):
        self.known_risks = [
            "Mobile crash on feature load",
            "Payment gateway integration issues",
            "API latency spikes under load",
            "Support capacity exceeded"
        ]

    def identify_risks(self, data_analysis: Dict, pm_analysis: Dict) -> Dict:
        """Challenge assumptions and highlight risks"""
        risks = []

        # Metric-based risks
        if data_analysis['trends']['dau']['change_pct'] < -10:
            risks.append({
                'risk': 'User flight risk',
                'impact': 'HIGH',
                'probability': 'HIGH',
                'mitigation': 'Pause rollout, investigate root cause'
            })

        if data_analysis['sentiment']['negative_ratio'] > 0.4:
            risks.append({
                'risk': 'Brand reputation damage',
                'impact': 'HIGH',
                'probability': 'MEDIUM',
                'mitigation': 'Transparent communication, rapid fixes'
            })

        # Add known risks that match current issues
        current_issues = ' '.join(data_analysis.get('key_takeaways', []))
        matching_known = [r for r in self.known_risks if any(word in current_issues.lower()
                                                             for word in r.lower().split())]

        return {
            'identified_risks': risks + [{'risk': r, 'impact': 'MEDIUM', 'mitigation': 'Monitor'}
                                       for r in matching_known],
            'unchallenged_assumptions': [
                "Assuming correlation = causation in metrics",
                "Sample size may be insufficient for confidence"
            ],
            'evidence_gaps': ['Long-term retention impact', 'Segmented user analysis']
        }



"""4. Orchestrator"""

import json
import yaml
import logging
from datetime import datetime
from pathlib import Path
import sys
from typing import Dict, Any

# Agent imports
from agents.product_manager import ProductManagerAgent
from agents.data_analyst import DataAnalystAgent
from agents.marketing_comms import MarketingCommsAgent
from agents.risk_critic import RiskCriticAgent

# Tool imports
from tools.metrics_analyzer import MetricsAnalyzer
from tools.sentiment_analyzer import SentimentAnalyzer

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s [%(levelname)s] %(name)s: %(message)s',
    handlers=[
        logging.FileHandler('warroom.log'),
        logging.StreamHandler(sys.stdout)
    ]
)
logger = logging.getLogger(__name__)

class WarRoomOrchestrator:
    def __init__(self, data_dir: str = "data"):
        self.data_dir = Path(data_dir)
        self.metrics_tool = MetricsAnalyzer(self.data_dir / "mock_dashboard.csv")
        self.sentiment_tool = SentimentAnalyzer(self.data_dir / "user_feedback.json")
        self.agents = {
            'pm': ProductManagerAgent("config.yaml"),
            'analyst': DataAnalystAgent(),
            'marketing': MarketingCommsAgent(),
            'risk': RiskCriticAgent()
        }
        self.trace = []

    def log_step(self, step: str, data: Dict = None):
        """Log each step for traceability"""
        timestamp = datetime.now().isoformat()
        entry = {'timestamp': timestamp, 'step': step, 'data': data}
        self.trace.append(entry)
        logger.info(f"STEP: {step} | Data: {json.dumps(data, indent=2)[:200]}...")

    def execute_war_room(self) -> Dict[str, Any]:
        """Main orchestration workflow"""
        logger.info("🚨 WAR ROOM CONVENED - PurpleMerit Launch Assessment")
        print("\n" + "="*80)
        print("🛡️  PURPLEMERIT WAR ROOM - PRODUCT LAUNCH DECISION")
        print("="*80)

#  1: Data Collection


def execute_war_room(self) -> Dict[str, Any]:
    logger.info("🚨 WAR ROOM CONVENED - PurpleMerit Launch Assessment")

    print("\n" + "="*80)
    print("🛡️  PURPLEMERIT WAR ROOM - PRODUCT LAUNCH DECISION")
    print("="*80)

    # ✅ Correct indentation starts here
    self.log_step("PHASE_1_DATA_COLLECTION", {})

    key_metrics = self.metrics_tool.get_key_metrics_summary()

    print(
        f"📊 KEY METRICS: DAU={key_metrics['latest_dau']} "
        f"(-{abs(key_metrics['dau_change_pct'])}%), "
        f"Crash={key_metrics['crash_rate']:.1%}, "
        f"Latency={key_metrics['latency_p95']}ms"
    )





def execute_war_room(self):

    # Phase 2: Parallel Agent Analysis
    self.log_step("PHASE_2_AGENT_ANALYSIS", {})

def execute_war_room(self):


    self.log_step("PHASE_2_AGENT_ANALYSIS", {})

    # Product Manager defines criteria
    pm_analysis = self.agents['pm'].analyze_success_criteria(self.metrics_tool)

    self.log_step(
        "PM_ANALYSIS_COMPLETE",
        {'success_criteria_met': pm_analysis['success_criteria_met']}
    )

def execute_war_room(self):

        # Data Analyst does deep dive
    analyst_analysis = self.agents['analyst'].comprehensive_analysis(
        self.metrics_tool,
        self.sentiment_tool
    )

def execute_war_room(self):

    analyst_analysis = self.agents['analyst'].comprehensive_analysis(
        self.metrics_tool, self.sentiment_tool
    )

    self.log_step("DATA_ANALYST_COMPLETE", {
        'confidence': analyst_analysis['confidence_score'],
        'concerning_metrics': len([
            k for k, v in analyst_analysis['trends'].items() if v['concerning']
        ])
    })

def execute_war_room(self):

    # Marketing assesses perception
    marketing_plan = self.agents['marketing'].craft_communication_plan(
        {'sentiment': analyst_analysis['sentiment']},
        analyst_analysis['key_takeaways']
    )

    self.log_step(
        "MARKETING_PLAN_READY",
        {'tier': marketing_plan['communication_tier']}
    )

def execute_war_room(self):

    # earlier steps
    pm_analysis = self.agents['pm'].analyze_success_criteria(self.metrics_tool)

    analyst_analysis = self.agents['analyst'].comprehensive_analysis(
        self.metrics_tool, self.sentiment_tool
    )

    # ✅ Risk critic
    risk_assessment = self.agents['risk'].identify_risks(
        analyst_analysis,
        pm_analysis
    )

    self.log_step(
        "RISK_ASSESSMENT_COMPLETE",
        {'risk_count': len(risk_assessment['identified_risks'])}
    )

def execute_war_room(self):

    # Phase 3: Decision Synthesis
    self.log_step("PHASE_3_DECISION_SYNTHESIS", {})

    decision = self._synthesize_decision(
        pm_analysis,
        analyst_analysis,
        risk_assessment
    )

def execute_war_room(self):

    # Phase 4: Final Output
    final_output = self._generate_structured_output(
        decision,
        pm_analysis,
        analyst_analysis,
        marketing_plan,
        risk_assessment,
        key_metrics
    )

    self._save_output(final_output)
    self._print_decision(final_output)

    logger.info("✅ WAR ROOM SESSION COMPLETE")
    return final_output

def _synthesize_decision(self, pm: Dict, analyst: Dict, risks: Dict) -> str:
        """Make final go/no-go decision"""
        confidence = analyst['confidence_score']
        critical_issues = len([r for r in risks['identified_risks'] if r['impact'] == 'HIGH'])
        dau_drop = analyst['trends']['dau']['change_pct']
        crash_rate = analyst['key_metrics']['crash_rate']

        if confidence < 40 or crash_rate > 0.02 or dau_drop < -15:
            return "PAUSE"
        elif critical_issues >= 2 or confidence < 60:
            return "PROCEED_WITH_MONITORING"
        else:
            return "PROCEED"

def _generate_structured_output(self, decision: str, pm: Dict, analyst: Dict,
                                  marketing: Dict, risks: Dict, metrics: Dict) -> Dict:
        """Generate final JSON/YAML output"""
        return {
            "timestamp": datetime.now().isoformat(),
            "decision": decision,
            "rationale": {
                "metric_drivers": [
                    f"DAU: {analyst['trends']['dau']['change_pct']}% {'↓' if analyst['trends']['dau']['change_pct'] < 0 else '↑'}",
                    f"Crash Rate: {metrics['crash_rate']:.1%} {'⚠️' if metrics['crash_rate'] > 0.015 else ''}",
                    f"Confidence: {analyst['confidence_score']:.0f}%"
                ],
                "feedback_summary": f"{analyst['sentiment']['negative_ratio']:.0%} negative sentiment"
            },
            "risk_register": risks['identified_risks'][:3],  # Top 3 risks
            "action_plan_24h": [
                {"action": "Hotfix payment flow", "owner": "Engineering", "priority": "P0"},
                {"action": "Mobile crash investigation", "owner": "Mobile Team", "priority": "P0"},
                {"action": "Status page update", "owner": "Comms", "priority": "P1"}
            ],
            "communication_plan": marketing['messaging'],
            "confidence_score": round(analyst['confidence_score'], 1),
            "confidence_improvers": [
                "24h metric stabilization",
                "Payment success >98%",
                "Crash rate <1%",
                "Support tickets trending down"
            ],
            "trace_summary": {
                "total_steps": len(self.trace),
                "critical_findings": len(risks['identified_risks'])
            }
        }

  def _save_output(self, output: Dict):
        """Save structured decision"""
        output_dir = Path("output")
        output_dir.mkdir(exist_ok=True)

def _save_output(self, output: Dict):
    """Save structured decision"""
    output_dir = Path("output")
    output_dir.mkdir(exist_ok=True)

    # JSON
    with open(output_dir / "launch_decision.json", 'w') as f:
        json.dump(output, f, indent=2)

    # YAML
    with open(output_dir / "launch_decision.yaml", 'w') as f:
        yaml.dump(output, f)

    # Trace
    with open(output_dir / "warroom_trace.json", 'w') as f:
        json.dump(self.trace, f, indent=2)

import json
from pathlib import Path

class SentimentAnalyzer:
    def __init__(self, file_path):
        self.file_path = Path(file_path)
        self.data = self._load_data()

    def _load_data(self):
        if not self.file_path.exists():
            print(f"❌ File not found: {self.file_path}")
            return []

        with open(self.file_path, "r", encoding="utf-8") as f:
            return json.load(f)

    def analyze_sentiment(self):
        positive, negative, neutral = 0, 0, 0

        for item in self.data:
            text = item.get("feedback", "").lower()

            if any(word in text for word in ["good", "great", "love", "excellent"]):
                positive += 1
            elif any(word in text for word in ["bad", "poor", "hate", "bug", "issue"]):
                negative += 1
            else:
                neutral += 1

        total = len(self.data) if self.data else 1

        return {
            "positive": positive,
            "negative": negative,
            "neutral": neutral,
            "total": total,
            "negative_ratio": negative / total
        }

class SentimentAnalyzer:
    def __init__(self, file_path):
        self.file_path = file_path

class ProductManagerAgent:
    def __init__(self, config_path=None):
        self.config_path = config_path

    def analyze_success_criteria(self, metrics_tool):
        return {
            "success_criteria_met": True
        }

def _print_decision(self, output: Dict):
    """Console-friendly decision display"""
    print("\n" + "📋" * 30)
    print(f"🎯 DECISION: {output['decision']}")
    print("📋" * 30)
    print(f"📈 DAU: {output['rationale']['metric_drivers'][0]}")
    print(f"💥 Crashes: {output['rationale']['metric_drivers'][1]}")
    print(f"🎭 Sentiment: {output['rationale']['feedback_summary']}")
    print(f"⚖️  Confidence: {output['confidence_score']}%")

    print("\n🔥 TOP RISKS:")
    for risk in output['risk_register']:
        print(f"  • {risk['risk']} ({risk['impact']})")

    print("\n⚡ 24H ACTION PLAN:")
    for action in output['action_plan_24h']:
        print(f"  {action['priority']}: {action['action']} → {action['owner']}")

    print("\n" + "📊" * 40 + "\n")


def main():
    orchestrator = WarRoomOrchestrator()
    result = orchestrator.execute_war_room()

    print("\n💾 Output saved to: output/launch_decision.json")
    print("📋 Full trace: output/warroom_trace.json")

    return result


if __name__ == "__main__":
    main()

